# Generated by Django 6.0.1 on 2026-01-27 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='광고할 제품/서비스', max_length=200, verbose_name='주제')),
                ('script', models.TextField(blank=True, help_text='선택적 줄거리/대본 (비어있으면 AI가 자동 생성)', verbose_name='스크립트')),
                ('product_image_url', models.URLField(blank=True, help_text='CTA 마지막 프레임에 포함될 제품 이미지', verbose_name='제품 이미지 URL')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('planning', '기획중'), ('preparing', '에셋 준비중'), ('generating', '영상 생성중'), ('concatenating', '병합중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('current_step', models.CharField(blank=True, max_length=100, verbose_name='현재 단계')),
                ('error_message', models.TextField(blank=True, verbose_name='에러 메시지')),
                ('script_json', models.JSONField(blank=True, null=True, verbose_name='생성된 시나리오')),
                ('product_detail', models.JSONField(blank=True, null=True, verbose_name='제품 정보')),
                ('character_details', models.JSONField(blank=True, null=True, verbose_name='캐릭터 정보')),
                ('first_frame', models.ImageField(blank=True, upload_to='frames/', verbose_name='Scene 1 첫 프레임')),
                ('scene1_last_frame', models.ImageField(blank=True, upload_to='frames/', verbose_name='Scene 1 마지막 프레임')),
                ('cta_last_frame', models.ImageField(blank=True, upload_to='frames/', verbose_name='CTA 마지막 프레임')),
                ('final_video', models.FileField(blank=True, upload_to='videos/', verbose_name='최종 영상')),
                ('skipped_segments', models.JSONField(blank=True, default=list, verbose_name='스킵된 세그먼트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '영상 생성 작업',
                'verbose_name_plural': '영상 생성 작업',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_index', models.PositiveSmallIntegerField(verbose_name='세그먼트 번호')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='제목')),
                ('seconds', models.PositiveSmallIntegerField(default=8, verbose_name='길이(초)')),
                ('prompt', models.TextField(blank=True, verbose_name='프롬프트')),
                ('video_file', models.FileField(blank=True, upload_to='segments/', verbose_name='세그먼트 영상')),
                ('last_frame', models.ImageField(blank=True, upload_to='frames/', verbose_name='마지막 프레임')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('generating', '생성중'), ('completed', '완료'), ('skipped', '스킵됨')], default='pending', max_length=20, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, verbose_name='에러 메시지')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='videos.videogenerationjob')),
            ],
            options={
                'verbose_name': '영상 세그먼트',
                'verbose_name_plural': '영상 세그먼트',
                'ordering': ['segment_index'],
                'unique_together': {('job', 'segment_index')},
            },
        ),
    ]
