# Generated by Django 6.0.1 on 2026-01-27 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='제품명/상호')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='브랜드')),
                ('description', models.TextField(blank=True, verbose_name='브랜드/제품 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='videogenerationjob',
            name='product_image_url',
            field=models.URLField(blank=True, help_text='제품을 선택하지 않고 직접 URL 입력 시 사용', verbose_name='제품 이미지 URL (직접 입력)'),
        ),
        migrations.AddField(
            model_name='videogenerationjob',
            name='product',
            field=models.ForeignKey(blank=True, help_text='연결할 제품 (제품 이미지가 CTA에 사용됨)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='videos.product', verbose_name='제품'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='이미지')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='대체 텍스트')),
                ('is_primary', models.BooleanField(default=False, verbose_name='대표 이미지')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='videos.product')),
            ],
            options={
                'verbose_name': '제품 이미지',
                'verbose_name_plural': '제품 이미지',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
