# Generated by Django 6.0.1 on 2026-01-27 06:15

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_product_alter_videogenerationjob_product_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('asset_type', models.CharField(choices=[('last_cta_image', '라스트 CTA 이미지'), ('sound_effect', '효과음')], max_length=20, verbose_name='에셋 타입')),
                ('file', models.FileField(upload_to='assets/', verbose_name='파일')),
                ('is_active', models.BooleanField(default=True, help_text='활성화된 에셋이 영상 생성에 사용됩니다. 타입별로 하나만 활성화 가능합니다.', verbose_name='활성화')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '영상 에셋',
                'verbose_name_plural': '영상 에셋',
                'ordering': ['asset_type', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='videogenerationjob',
            name='cta_last_frame',
            field=models.ImageField(blank=True, upload_to=videos.models.job_frame_path, verbose_name='CTA 마지막 프레임'),
        ),
        migrations.AlterField(
            model_name='videogenerationjob',
            name='final_video',
            field=models.FileField(blank=True, upload_to=videos.models.job_video_path, verbose_name='최종 영상'),
        ),
        migrations.AlterField(
            model_name='videogenerationjob',
            name='first_frame',
            field=models.ImageField(blank=True, upload_to=videos.models.job_frame_path, verbose_name='Scene 1 첫 프레임'),
        ),
        migrations.AlterField(
            model_name='videogenerationjob',
            name='scene1_last_frame',
            field=models.ImageField(blank=True, upload_to=videos.models.job_frame_path, verbose_name='Scene 1 마지막 프레임'),
        ),
        migrations.AlterField(
            model_name='videosegment',
            name='last_frame',
            field=models.ImageField(blank=True, upload_to=videos.models.segment_frame_path, verbose_name='마지막 프레임'),
        ),
        migrations.AlterField(
            model_name='videosegment',
            name='video_file',
            field=models.FileField(blank=True, upload_to=videos.models.segment_video_path, verbose_name='세그먼트 영상'),
        ),
    ]
