# Generated by Django 6.0.1 on 2026-01-27 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_add_video_asset_and_job_folder_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogenerationjob',
            name='last_cta_asset',
            field=models.ForeignKey(blank=True, help_text='선택하지 않으면 기본 활성화된 에셋 사용', limit_choices_to={'asset_type': 'last_cta_image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_as_cta', to='videos.videoasset', verbose_name='라스트 CTA 이미지'),
        ),
        migrations.AddField(
            model_name='videogenerationjob',
            name='sound_effect_asset',
            field=models.ForeignKey(blank=True, help_text='선택하지 않으면 기본 활성화된 에셋 사용', limit_choices_to={'asset_type': 'sound_effect'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_as_sound', to='videos.videoasset', verbose_name='효과음'),
        ),
    ]
