# Generated by Django 6.0.1 on 2026-01-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_add_video_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogenerationjob',
            name='failed_at_status',
            field=models.CharField(blank=True, help_text='실패 시 어느 단계에서 실패했는지 기록 (재개 시 사용)', max_length=20, verbose_name='실패 시점 상태'),
        ),
        migrations.AlterField(
            model_name='videogenerationjob',
            name='status',
            field=models.CharField(choices=[('pending', '대기중'), ('planning', '기획중'), ('preparing', '첫 프레임 생성중'), ('generating_s1', 'Scene 1 생성중'), ('preparing_cta', 'CTA 프레임 생성중'), ('generating_s2', 'Scene 2 생성중'), ('concatenating', '병합중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태'),
        ),
    ]
