# Generated by Django 6.0.1 on 2026-02-03 07:57

import django.db.models.deletion
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_add_granular_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogenerationjob',
            name='character_description',
            field=models.TextField(blank=True, help_text='AI가 분석한 캐릭터 외형 설명', verbose_name='캐릭터 분석 결과'),
        ),
        migrations.AddField(
            model_name='videogenerationjob',
            name='character_image',
            field=models.ImageField(blank=True, help_text='게임 캐릭터 이미지 (게임 타입 전용)', upload_to='game_characters/', verbose_name='캐릭터 이미지'),
        ),
        migrations.AddField(
            model_name='videogenerationjob',
            name='game_locations_used',
            field=models.JSONField(blank=True, default=list, help_text='스크립트에 사용된 게임 내 장소 목록', verbose_name='사용된 게임 장소'),
        ),
        migrations.AddField(
            model_name='videogenerationjob',
            name='game_name',
            field=models.CharField(blank=True, help_text='캐릭터가 들어갈 게임 이름 (예: PUBG, 원신)', max_length=200, verbose_name='게임명'),
        ),
        migrations.AddField(
            model_name='videogenerationjob',
            name='job_type',
            field=models.CharField(choices=[('drama', '드라마타이즈 광고'), ('game', '게임 캐릭터 숏폼')], default='drama', max_length=20, verbose_name='작업 유형'),
        ),
        migrations.AddField(
            model_name='videogenerationjob',
            name='user_prompt',
            field=models.TextField(blank=True, help_text='영상에 대한 추가 요청사항', verbose_name='추가 프롬프트'),
        ),
        migrations.AlterField(
            model_name='videogenerationjob',
            name='last_cta_asset',
            field=models.ForeignKey(blank=True, help_text='선택하지 않으면 기본 활성화된 에셋 사용 (드라마 타입 전용)', limit_choices_to={'asset_type': 'last_cta_image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_as_cta', to='videos.videoasset', verbose_name='라스트 CTA 이미지'),
        ),
        migrations.AlterField(
            model_name='videogenerationjob',
            name='sound_effect_asset',
            field=models.ForeignKey(blank=True, help_text='선택하지 않으면 기본 활성화된 에셋 사용 (드라마 타입 전용)', limit_choices_to={'asset_type': 'sound_effect'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_as_sound', to='videos.videoasset', verbose_name='효과음'),
        ),
        migrations.AlterField(
            model_name='videogenerationjob',
            name='status',
            field=models.CharField(choices=[('pending', '대기중'), ('planning', '기획중'), ('completed', '완료'), ('failed', '실패'), ('preparing', '첫 프레임 생성중'), ('generating_s1', 'Scene 1 생성중'), ('preparing_cta', 'CTA 프레임 생성중'), ('generating_s2', 'Scene 2 생성중'), ('concatenating', '병합중'), ('generating_frames', '프레임 생성중'), ('generating_videos', '영상 생성중'), ('merging', '영상 병합중')], default='pending', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='videogenerationjob',
            name='video_style',
            field=models.CharField(choices=[('makjang_drama', 'B급 막장 드라마'), ('lotteria_story', '롯데리아형 스토리')], default='makjang_drama', help_text='영상 스타일 템플릿', max_length=50, verbose_name='영상 스타일'),
        ),
        migrations.CreateModel(
            name='GameFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_number', models.PositiveSmallIntegerField(verbose_name='씬 번호')),
                ('shot_type', models.CharField(blank=True, max_length=50, verbose_name='샷 타입')),
                ('game_location', models.CharField(blank=True, max_length=200, verbose_name='게임 장소')),
                ('prompt', models.TextField(verbose_name='영상 생성 프롬프트')),
                ('action', models.CharField(blank=True, max_length=200, verbose_name='액션')),
                ('camera', models.CharField(blank=True, max_length=200, verbose_name='카메라 움직임')),
                ('description_kr', models.TextField(blank=True, verbose_name='한글 설명')),
                ('image_file', models.ImageField(blank=True, upload_to=videos.models.game_frame_image_path, verbose_name='시작 프레임 이미지')),
                ('image_url', models.URLField(blank=True, verbose_name='이미지 URL')),
                ('video_file', models.FileField(blank=True, upload_to=videos.models.game_segment_video_path, verbose_name='생성된 영상')),
                ('video_url', models.URLField(blank=True, verbose_name='영상 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_frames', to='videos.videogenerationjob', verbose_name='영상 작업')),
            ],
            options={
                'verbose_name': '게임 프레임',
                'verbose_name_plural': '게임 프레임',
                'ordering': ['scene_number'],
                'unique_together': {('job', 'scene_number')},
            },
        ),
    ]
